# Generated by Django 4.2.7 on 2025-07-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('category', models.CharField(choices=[('corporate', 'Corporate Structures'), ('holding', 'Holding Companies'), ('trust', 'Trust Structures'), ('partnership', 'Partnership Entities'), ('foundation', 'Foundation Structures'), ('llc', 'LLC Structures')], max_length=50, verbose_name='Category')),
                ('jurisdiction', models.CharField(choices=[('bahamas', 'Bahamas'), ('bvi', 'British Virgin Islands'), ('cayman', 'Cayman Islands'), ('nevis', 'Nevis'), ('delaware', 'Delaware, USA'), ('nevada', 'Nevada, USA'), ('wyoming', 'Wyoming, USA'), ('singapore', 'Singapore'), ('hong_kong', 'Hong Kong'), ('switzerland', 'Switzerland')], max_length=50, verbose_name='Jurisdiction')),
                ('description', models.TextField(verbose_name='Description')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Entity Type')),
                ('default_name_pattern', models.CharField(max_length=200, verbose_name='Default Name Pattern')),
                ('default_attributes', models.JSONField(default=dict, verbose_name='Default Attributes')),
                ('required_documents', models.JSONField(default=list, verbose_name='Required Documents')),
                ('typical_uses', models.JSONField(default=list, verbose_name='Typical Uses')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity Template',
                'verbose_name_plural': 'Entity Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickAddPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Preset Name')),
                ('quick_name_prefix', models.CharField(blank=True, max_length=100, verbose_name='Quick Name Prefix')),
                ('auto_number', models.BooleanField(default=True, verbose_name='Auto Number')),
                ('preset_attributes', models.JSONField(default=dict, verbose_name='Preset Attributes')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.entitytemplate', verbose_name='Base Template')),
            ],
            options={
                'verbose_name': 'Quick Add Preset',
                'verbose_name_plural': 'Quick Add Presets',
                'ordering': ['-is_favorite', '-usage_count', 'name'],
            },
        ),
    ]
