# Generated by Django 4.2.7 on 2025-07-09 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('corporate', '0003_entitytemplate_quickaddpreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(help_text='Custom name for this specific instance', max_length=200)),
                ('total_shares', models.PositiveIntegerField(help_text='Total number of shares for this instance')),
                ('corporate_name', models.CharField(blank=True, help_text='Official corporate name for this instance', max_length=200)),
                ('hash_number', models.CharField(blank=True, help_text='Registration or hash number', max_length=50)),
                ('level', models.PositiveIntegerField(help_text='Level in the structure hierarchy (1 = top level)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_template', models.ForeignKey(help_text='Entity template this node is based on', on_delete=django.db.models.deletion.CASCADE, related_name='structure_instances', to='corporate.entity')),
                ('parent_node', models.ForeignKey(blank=True, help_text='Parent node in the hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='corporate.structurenode')),
                ('structure', models.ForeignKey(help_text='Structure this node belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='corporate.structure')),
            ],
            options={
                'verbose_name': 'Structure Node',
                'verbose_name_plural': 'Structure Nodes',
                'ordering': ['level', 'custom_name'],
                'unique_together': {('structure', 'custom_name')},
            },
        ),
        migrations.CreateModel(
            name='NodeOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (0.01 to 100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('owned_shares', models.PositiveIntegerField(help_text='Number of shares owned')),
                ('share_value_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Value per share in USD', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_node', models.ForeignKey(help_text='Node being owned', on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='corporate.structurenode')),
                ('owner_node', models.ForeignKey(blank=True, help_text='Node that owns this node (Entity→Entity)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_nodes', to='corporate.structurenode')),
                ('owner_party', models.ForeignKey(blank=True, help_text='Party that owns this node (UBO)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_nodes', to='parties.party')),
            ],
            options={
                'verbose_name': 'Node Ownership',
                'verbose_name_plural': 'Node Ownerships',
                'ordering': ['-ownership_percentage'],
            },
        ),
    ]
